### ISSUE TITLE
[performance] iroha2.IrohaClientException when applying load at 1.18 rps

### ISSUE THREAD

**Issue by timofeevmd** [hyperledger/iroha-java#389]
Environment
```bash
CPU
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) E-2278G CPU @ 3.40GHz
    CPU family:          6
    Model:               158
    Thread(s) per core:  2
    Core(s) per socket:  8
    Socket(s):           1
    
Memory
RANGE                                  SIZE  STATE REMOVABLE  BLOCK
0x0000000000000000-0x000000008fffffff  2.3G online       yes   0-17
0x0000000100000000-0x000000086fffffff 29.8G online       yes 32-269

Memory block size:       128M
Total online memory:      32G
Total offline memory:      0B
```

**link to performance result**

1. performance generator dashboard - https://grafana.soramitsu.co.jp/d/e07e41e6-8aab-4e3e-9a4b-a50bfce77dd3/iroha2-gatling-performance-dashboard?orgId=1&from=1699973006243&to=1699984516051&var-quantile=95&var-transaction=account_register_perf_bucket&var-performances=transfer_asset_performance_total

2. iroha2 dashboard - https://grafana.soramitsu.co.jp/d/1kmsWQQ4z/iroha2-qa?orgId=1&var-namespace=iroha2-test&from=1699973006000&to=1699984516000

3. kubernetes dashboard - https://grafana.soramitsu.co.jp/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&var-datasource=default&var-project=tachi&var-namespace=iroha2-test&var-pod=iroha2-0&from=1699973006000&to=1699984516000

- when applying a load of 1.18 requests per second javaSDK gives an error
- CPU and RAM utilization on the load generator does not exceed reference values

- **precondition test**

1. create 3 domains
4. create 45 users in each domain
5. for each user mint 10000 assets

- **test script**

1. execution of a transaction transfer of an asset from random user to random user

iroha2 logdata
https://opensearch.soramitsu.co.jp/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-14T10:48:29.000Z',to:'2023-11-14T10:50:29.000Z'))&_a=(columns:!(kubernetes.pod.name,logdata),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'155ed930-ca2d-11ed-8130-f19d88adb388',key:kubernetes.namespace,negate:!f,params:(query:iroha2-test),type:phrase),query:(match_phrase:(kubernetes.namespace:iroha2-test))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'155ed930-ca2d-11ed-8130-f19d88adb388',key:kubernetes.container.name,negate:!f,params:!(iroha2),type:phrases,value:iroha2),query:(bool:(minimum_should_match:1,should:!((match_phrase:(kubernetes.container.name:iroha2))))))),index:'155ed930-ca2d-11ed-8130-f19d88adb388',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',asc))
)

```bash
logdata | warp::filters::trace: unable to serve request (client error) status=404 error=Some(Rejection(NotFound))
-- | --
```

```bash
2023-11-14 14:49:30.108 [DEBUG] j.c.s.i.c.Iroha2Client - Creating subscription to transaction status: e97de256748cf0d113fcf875809933a75ebba8724b89c88ec8ccd4a622456aab
SEND_TRANSACTION: TRANSFER ASSET
2023-11-14 14:49:30.108 [DEBUG] j.c.s.i.c.Iroha2Client - Creating subscription to transaction status: ff7e670415ec4a9ee605ac48fa4f8eadff46f1631e720089c162b06b6d892c87
2023-11-14 14:49:30.174 [DEBUG] j.c.s.i.c.Iroha2Client - Transaction 82a5361865b42b0d460c657de043e19e01fa958a13e4501b6c0ff68852be3c57 committed
Exception in thread "DefaultDispatcher-worker-10" java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:37)
	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:42)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:32)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:194)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:231)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:910)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:867)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:832)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: jp.co.soramitsu.iroha2.IrohaClientException
		at jp.co.soramitsu.iroha2.client.Iroha2Client$client$2$1$4$1.invokeSuspend(Iroha2Client.kt:180)
		at jp.co.soramitsu.iroha2.client.Iroha2Client$client$2$1$4$1.invoke(Iroha2Client.kt)
		at jp.co.soramitsu.iroha2.client.Iroha2Client$client$2$1$4$1.invoke(Iroha2Client.kt)
		at io.ktor.client.plugins.HttpCallValidator.processException(HttpCallValidator.kt:59)
		at io.ktor.client.plugins.HttpCallValidator.access$processException(HttpCallValidator.kt:43)
		at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:133)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		... 7 more
	Caused by: java.util.concurrent.CancellationException: StandaloneCoroutine was cancelled
		at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt:97)
		at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt:95)
		at kotlinx.coroutines.InvokeOnCancelling.invoke(JobSupport.kt:1431)
		at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1477)
		at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:799)
		at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:759)
		at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:675)
		at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:636)
		at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:621)
		at kotlinx.coroutines.Job$DefaultImpls.cancel$default(Job.kt:199)
		at kotlinx.coroutines.JobKt__JobKt.cancelAndJoin(Job.kt:511)
		at kotlinx.coroutines.JobKt.cancelAndJoin(Unknown Source)
		at jp.co.soramitsu.iroha2.client.blockstream.BlockStreamSubscription$stop$2.invokeSuspend(BlockStreamSubscription.kt:92)
		at jp.co.soramitsu.iroha2.client.blockstream.BlockStreamSubscription$stop$2.invoke(BlockStreamSubscription.kt)
		at jp.co.soramitsu.iroha2.client.blockstream.BlockStreamSubscription$stop$2.invoke(BlockStreamSubscription.kt)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
		at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
		at jp.co.soramitsu.iroha2.client.blockstream.BlockStreamSubscription.stop(BlockStreamSubscription.kt:90)
		at jp.co.soramitsu.iroha2.client.blockstream.BlockStreamSubscription$close$1.invokeSuspend(BlockStreamSubscription.kt:99)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
		at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
		at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
		at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
		at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
		at jp.co.soramitsu.iroha2.client.blockstream.BlockStreamSubscription.close(BlockStreamSubscription.kt:99)
		at jp.co.soramitsu.load.TransactionOnly$transferAssetsOnlyScn$2$1.invokeSuspend(TransactionOnly.kt:84)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
		at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
		at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
		at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
		at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
		at jp.co.soramitsu.load.TransactionOnly.transferAssetsOnlyScn$lambda$1(TransactionOnly.kt:76)
		at io.gatling.javaapi.core.internal.exec.ScalaExecs$.$anonfun$apply$3(ScalaExecs.scala:33)
		at io.gatling.commons.validation.package$.safely(package.scala:30)
		at io.gatling.javaapi.core.internal.exec.ScalaExecs$.$anonfun$apply$2(ScalaExecs.scala:33)
		at io.gatling.core.action.SessionHook.execute(SessionHook.scala:38)
		at io.gatling.core.action.Action.$bang(Action.scala:42)
		at io.gatling.core.action.Action.$bang$(Action.scala:39)
		at io.gatling.core.action.SessionHook.io$gatling$core$action$ChainableAction$$super$$bang(SessionHook.scala:23)
		at io.gatling.core.action.ChainableAction.$bang(Action.scala:73)
		at io.gatling.core.action.ChainableAction.$bang$(Action.scala:71)
		at io.gatling.core.action.builder.SessionHookBuilder$$anon$1.io$gatling$core$action$ExitableAction$$super$$bang(SessionHookBuilder.scala:28)
		at io.gatling.core.action.ExitableAction.$bang(Action.scala:110)
		at io.gatling.core.action.ExitableAction.$bang$(Action.scala:107)
		at io.gatling.core.action.builder.SessionHookBuilder$$anon$1.$bang(SessionHookBuilder.scala:28)
		at io.gatling.core.action.SessionHook.$anonfun$execute$1(SessionHook.scala:38)
		at io.gatling.core.action.SessionHook.$anonfun$execute$1$adapted(SessionHook.scala:38)
		at io.gatling.commons.validation.Success.map(Validation.scala:41)
		at io.gatling.core.action.SessionHook.execute(SessionHook.scala:38)
		at io.gatling.core.action.Action.$bang(Action.scala:42)
		at io.gatling.core.action.Action.$bang$(Action.scala:39)
		at io.gatling.core.action.SessionHook.io$gatling$core$action$ChainableAction$$super$$bang(SessionHook.scala:23)
		at io.gatling.core.action.ChainableAction.$bang(Action.scala:73)
		at io.gatling.core.action.ChainableAction.$bang$(Action.scala:71)
		at io.gatling.core.action.builder.SessionHookBuilder$$anon$1.io$gatling$core$action$ExitableAction$$super$$bang(SessionHookBuilder.scala:28)
		at io.gatling.core.action.ExitableAction.$bang(Action.scala:110)
		at io.gatling.core.action.ExitableAction.$bang$(Action.scala:107)
		at io.gatling.core.action.builder.SessionHookBuilder$$anon$1.$bang(SessionHookBuilder.scala:28)
		at io.gatling.core.action.InnerLoop.$anonfun$execute$1(Loop.scala:89)
		at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: android/os/Build$VERSION
	at kotlinx.coroutines.android.AndroidExceptionPreHandler.handleException(AndroidExceptionPreHandler.kt:47)
	at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:38)
	... 15 more
Exception in thread "DefaultDispatcher-worker-10" jp.co.soramitsu.iroha2.IrohaClientException
	at jp.co.soramitsu.iroha2.client.Iroha2Client$client$2$1$4$1.invokeSuspend(Iroha2Client.kt:180)
	at jp.co.soramitsu.iroha2.client.Iroha2Client$client$2$1$4$1.invoke(Iroha2Client.kt)
	at jp.co.soramitsu.iroha2.client.Iroha2Client$client$2$1$4$1.invoke(Iroha2Client.kt)
	at io.ktor.client.plugins.HttpCallValidator.processException(HttpCallValidator.kt:59)
	at io.ktor.client.plugins.HttpCallValidator.access$processException(HttpCallValidator.kt:43)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:133)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@473abbc0, Dispatchers.IO]
Caused by: java.util.concurrent.CancellationException: StandaloneCoroutine was cancelled
	at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt:97)
	at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt:95)
	at kotlinx.coroutines.InvokeOnCancelling.invoke(JobSupport.kt:1431)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1477)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:799)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:759)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:675)
	at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:636)
	at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:621)
	at kotlinx.coroutines.Job$DefaultImpls.cancel$default(Job.kt:199)
	at kotlinx.coroutines.JobKt__JobKt.cancelAndJoin(Job.kt:511)
	at kotlinx.coroutines.JobKt.cancelAndJoin(Unknown Source)
	at jp.co.soramitsu.iroha2.client.blockstream.BlockStreamSubscription$stop$2.invokeSuspend(BlockStreamSubscription.kt:92)
	at jp.co.soramitsu.iroha2.client.blockstream.BlockStreamSubscription$stop$2.invoke(BlockStreamSubscription.kt)
	at jp.co.soramitsu.iroha2.client.blockstream.BlockStreamSubscription$stop$2.invoke(BlockStreamSubscription.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at jp.co.soramitsu.iroha2.client.blockstream.BlockStreamSubscription.stop(BlockStreamSubscription.kt:90)
	at jp.co.soramitsu.iroha2.client.blockstream.BlockStreamSubscription$close$1.invokeSuspend(BlockStreamSubscription.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at jp.co.soramitsu.iroha2.client.blockstream.BlockStreamSubscription.close(BlockStreamSubscription.kt:99)
	at jp.co.soramitsu.load.TransactionOnly$transferAssetsOnlyScn$2$1.invokeSuspend(TransactionOnly.kt:84)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at jp.co.soramitsu.load.TransactionOnly.transferAssetsOnlyScn$lambda$1(TransactionOnly.kt:76)
	at io.gatling.javaapi.core.internal.exec.ScalaExecs$.$anonfun$apply$3(ScalaExecs.scala:33)
	at io.gatling.commons.validation.package$.safely(package.scala:30)
	at io.gatling.javaapi.core.internal.exec.ScalaExecs$.$anonfun$apply$2(ScalaExecs.scala:33)
	at io.gatling.core.action.SessionHook.execute(SessionHook.scala:38)
	at io.gatling.core.action.Action.$bang(Action.scala:42)
	at io.gatling.core.action.Action.$bang$(Action.scala:39)
	at io.gatling.core.action.SessionHook.io$gatling$core$action$ChainableAction$$super$$bang(SessionHook.scala:23)
	at io.gatling.core.action.ChainableAction.$bang(Action.scala:73)
	at io.gatling.core.action.ChainableAction.$bang$(Action.scala:71)
	at io.gatling.core.action.builder.SessionHookBuilder$$anon$1.io$gatling$core$action$ExitableAction$$super$$bang(SessionHookBuilder.scala:28)
	at io.gatling.core.action.ExitableAction.$bang(Action.scala:110)
	at io.gatling.core.action.ExitableAction.$bang$(Action.scala:107)
	at io.gatling.core.action.builder.SessionHookBuilder$$anon$1.$bang(SessionHookBuilder.scala:28)
	at io.gatling.core.action.SessionHook.$anonfun$execute$1(SessionHook.scala:38)
	at io.gatling.core.action.SessionHook.$anonfun$execute$1$adapted(SessionHook.scala:38)
	at io.gatling.commons.validation.Success.map(Validation.scala:41)
	at io.gatling.core.action.SessionHook.execute(SessionHook.scala:38)
	at io.gatling.core.action.Action.$bang(Action.scala:42)
	at io.gatling.core.action.Action.$bang$(Action.scala:39)
	at io.gatling.core.action.SessionHook.io$gatling$core$action$ChainableAction$$super$$bang(SessionHook.scala:23)
	at io.gatling.core.action.ChainableAction.$bang(Action.scala:73)
	at io.gatling.core.action.ChainableAction.$bang$(Action.scala:71)
	at io.gatling.core.action.builder.SessionHookBuilder$$anon$1.io$gatling$core$action$ExitableAction$$super$$bang(SessionHookBuilder.scala:28)
	at io.gatling.core.action.ExitableAction.$bang(Action.scala:110)
	at io.gatling.core.action.ExitableAction.$bang$(Action.scala:107)
	at io.gatling.core.action.builder.SessionHookBuilder$$anon$1.$bang(SessionHookBuilder.scala:28)
	at io.gatling.core.action.InnerLoop.$anonfun$execute$1(Loop.scala:89)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-11-14 14:49:30.179 [INFO ] j.c.s.i.c.b.BlockStreamSubscription - Unsubscribed from block streaming
2023-11-14 14:49:30.179 [WARN ] j.c.s.i.c.b.BlockStreamSubscription - Block streaming is already closed
2023-11-14 14:49:30.181 [DEBUG] j.c.s.i.c.b.BlockStreamSubscription - Expanding subscription with 1 storages
2023-11-14 14:49:30.181 [DEBUG] j.c.s.i.c.b.BlockStreamSubscription - Block stream subscription has been expanded. Updated number of channels is 1
```

**Comment by Erigara** [comment]
Opened hyperledger/iroha#4097 which removes from the logs.

```
warp::filters::trace: unable to serve request (client error) status=404 error=Some(Rejection(NotFound))
```

It was irrelevant noise.
